//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// Nom du fichier d'origine :
// Date de génération : 15/11/2016 14:46:42
namespace AstonEcole.oDataClient.ServiceReference1
{
    
    /// <summary>
    /// Il n'existe aucun commentaire pour Container dans le schéma.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisez un nouvel objet Container.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Étant donné que l'espace de noms configuré pour cette référence de service
        /// dans Visual Studio est différent de celui indiqué dans le
        /// schéma du serveur, utilisez des mappeurs de type pour effectuer des mappages entre les deux.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "AstonEcole.DTO", "AstonEcole.oDataClient.ServiceReference1");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Étant donné que l'espace de noms configuré pour cette référence de service
        /// dans Visual Studio est différent de celui indiqué dans le
        /// schéma du serveur, utilisez des mappeurs de type pour effectuer des mappages entre les deux.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("AstonEcole.oDataClient.ServiceReference1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("AstonEcole.DTO.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Students dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Student> Students
        {
            get
            {
                if ((this._Students == null))
                {
                    this._Students = base.CreateQuery<Student>("Students");
                }
                return this._Students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Student> _Students;
        /// <summary>
        /// Il n'existe aucun commentaire pour Courses dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Course> Courses
        {
            get
            {
                if ((this._Courses == null))
                {
                    this._Courses = base.CreateQuery<Course>("Courses");
                }
                return this._Courses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Course> _Courses;
        /// <summary>
        /// Il n'existe aucun commentaire pour Students dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour Courses dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCourses(Course course)
        {
            base.AddObject("Courses", course);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"AstonEcole.DTO\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\">" +
                "<EntityType Name=\"Student\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"I" +
                "d\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"FirstName\" Type=\"Edm.Stri" +
                "ng\" /><NavigationProperty Name=\"Courses\" Relationship=\"AstonEcole.DTO.AstonEcole" +
                "_DTO_Student_Courses_AstonEcole_DTO_Course_CoursesPartner\" ToRole=\"Courses\" From" +
                "Role=\"CoursesPartner\" /></EntityType><EntityType Name=\"Course\"><Key><PropertyRef" +
                " Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Prop" +
                "erty Name=\"Subject\" Type=\"Edm.String\" /><NavigationProperty Name=\"Students\" Rela" +
                "tionship=\"AstonEcole.DTO.AstonEcole_DTO_Course_Students_AstonEcole_DTO_Student_S" +
                "tudentsPartner\" ToRole=\"Students\" FromRole=\"StudentsPartner\" /><NavigationProper" +
                "ty Name=\"Teacher\" Relationship=\"AstonEcole.DTO.AstonEcole_DTO_Course_Teacher_Ast" +
                "onEcole_DTO_Teacher_TeacherPartner\" ToRole=\"Teacher\" FromRole=\"TeacherPartner\" /" +
                "></EntityType><EntityType Name=\"Teacher\"><Key><PropertyRef Name=\"Id\" /></Key><Pr" +
                "operty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=" +
                "\"Edm.String\" /><NavigationProperty Name=\"Courses\" Relationship=\"AstonEcole.DTO.A" +
                "stonEcole_DTO_Teacher_Courses_AstonEcole_DTO_Course_CoursesPartner\" ToRole=\"Cour" +
                "ses\" FromRole=\"CoursesPartner\" /></EntityType><Association Name=\"AstonEcole_DTO_" +
                "Student_Courses_AstonEcole_DTO_Course_CoursesPartner\"><End Type=\"AstonEcole.DTO." +
                "Course\" Role=\"Courses\" Multiplicity=\"*\" /><End Type=\"AstonEcole.DTO.Student\" Rol" +
                "e=\"CoursesPartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"AstonE" +
                "cole_DTO_Course_Students_AstonEcole_DTO_Student_StudentsPartner\"><End Type=\"Asto" +
                "nEcole.DTO.Student\" Role=\"Students\" Multiplicity=\"*\" /><End Type=\"AstonEcole.DTO" +
                ".Course\" Role=\"StudentsPartner\" Multiplicity=\"0..1\" /></Association><Association" +
                " Name=\"AstonEcole_DTO_Course_Teacher_AstonEcole_DTO_Teacher_TeacherPartner\"><End" +
                " Type=\"AstonEcole.DTO.Teacher\" Role=\"Teacher\" Multiplicity=\"0..1\" /><End Type=\"A" +
                "stonEcole.DTO.Course\" Role=\"TeacherPartner\" Multiplicity=\"0..1\" /></Association>" +
                "<Association Name=\"AstonEcole_DTO_Teacher_Courses_AstonEcole_DTO_Course_CoursesP" +
                "artner\"><End Type=\"AstonEcole.DTO.Course\" Role=\"Courses\" Multiplicity=\"*\" /><End" +
                " Type=\"AstonEcole.DTO.Teacher\" Role=\"CoursesPartner\" Multiplicity=\"0..1\" /></Ass" +
                "ociation></Schema><Schema Namespace=\"Default\" xmlns=\"http://schemas.microsoft.co" +
                "m/ado/2009/11/edm\"><EntityContainer Name=\"Container\" m:IsDefaultEntityContainer=" +
                "\"true\"><EntitySet Name=\"Students\" EntityType=\"AstonEcole.DTO.Student\" /><EntityS" +
                "et Name=\"Courses\" EntityType=\"AstonEcole.DTO.Course\" /><AssociationSet Name=\"Ast" +
                "onEcole_DTO_Student_Courses_AstonEcole_DTO_Course_CoursesPartnerSet\" Association" +
                "=\"AstonEcole.DTO.AstonEcole_DTO_Student_Courses_AstonEcole_DTO_Course_CoursesPar" +
                "tner\"><End Role=\"CoursesPartner\" EntitySet=\"Students\" /><End Role=\"Courses\" Enti" +
                "tySet=\"Courses\" /></AssociationSet><AssociationSet Name=\"AstonEcole_DTO_Course_S" +
                "tudents_AstonEcole_DTO_Student_StudentsPartnerSet\" Association=\"AstonEcole.DTO.A" +
                "stonEcole_DTO_Course_Students_AstonEcole_DTO_Student_StudentsPartner\"><End Role=" +
                "\"StudentsPartner\" EntitySet=\"Courses\" /><End Role=\"Students\" EntitySet=\"Students" +
                "\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>" +
                "";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour AstonEcole.DTO.Student dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Students")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Student : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Student.
        /// </summary>
        /// <param name="ID">Valeur initiale de Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Student CreateStudent(int ID)
        {
            Student student = new Student();
            student.Id = ID;
            return student;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Id dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété FirstName dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Courses dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Course> Courses
        {
            get
            {
                return this._Courses;
            }
            set
            {
                this._Courses = value;
                this.OnPropertyChanged("Courses");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Course> _Courses = new global::System.Data.Services.Client.DataServiceCollection<Course>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour AstonEcole.DTO.Course dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Courses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Course : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Course.
        /// </summary>
        /// <param name="ID">Valeur initiale de Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Course CreateCourse(int ID)
        {
            Course course = new Course();
            course.Id = ID;
            return course;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Id dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Subject dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this._Subject = value;
                this.OnSubjectChanged();
                this.OnPropertyChanged("Subject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Students dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Student> Students
        {
            get
            {
                return this._Students;
            }
            set
            {
                this._Students = value;
                this.OnPropertyChanged("Students");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Student> _Students = new global::System.Data.Services.Client.DataServiceCollection<Student>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Il n'existe aucun commentaire pour Teacher dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Teacher Teacher
        {
            get
            {
                return this._Teacher;
            }
            set
            {
                this._Teacher = value;
                this.OnPropertyChanged("Teacher");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Teacher _Teacher;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Il n'existe aucun commentaire pour AstonEcole.DTO.Teacher dans le schéma.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Teacher : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Créez un nouvel objet Teacher.
        /// </summary>
        /// <param name="ID">Valeur initiale de Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Teacher CreateTeacher(int ID)
        {
            Teacher teacher = new Teacher();
            teacher.Id = ID;
            return teacher;
        }
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Id dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour la propriété Name dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// Il n'existe aucun commentaire pour Courses dans le schéma.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Course> Courses
        {
            get
            {
                return this._Courses;
            }
            set
            {
                this._Courses = value;
                this.OnPropertyChanged("Courses");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Course> _Courses = new global::System.Data.Services.Client.DataServiceCollection<Course>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
